name: Tunnel Server 3

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Start Server
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 5
          echo "Testing local server"
          curl http://127.0.0.1:4040

      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Test server
        run: |
         nohup node server.js &
         sleep 5
         curl http://127.0.0.1:4040
    
      - name: Start Tunnel (Debug Mode)
        run: |
          cloudflared tunnel --url http://127.0.0.1:4040 --loglevel debug


