- name: Download cloudflared

- name: Download cloudflared2
run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared-linux-amd64
          sudo mv cloudflared-linux-amd64 /usr/local/bin/cloudflared

      - name: Start tunnel
        run: |
          cloudflared tunnel --url http://localhost:3000
